# Generated by Django 4.1.5 on 2023-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_code",
            field=models.IntegerField(null=True),
        ),
    ]
