# Generated by Django 4.1.5 on 2023-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="isAdm",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profileImg",
        ),
        migrations.AddField(
            model_name="user",
            name="is_adm",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
