# Generated by Django 4.1.5 on 2023-01-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_isadm_remove_user_profileimg_user_is_adm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
