# Generated by Django 4.1.5 on 2023-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_code",
            field=models.IntegerField(null=True),
        ),
    ]
