# Generated by Django 4.1.5 on 2023-01-03 17:03

from django.db import migrations


def populate_room_types(apps, schema_editor):
    data = [
        {
            "title": "Quarto Compartilhado",
            "description": "Ótimo custo benefício, essa opção é ideal para você que deseja que o seu pet interaja com outros catioros!",
            "image": "https://storage.googleapis.com/cmsapi.sistema.cim.br/C-307MMTG2XWCYRO/2021-05/ZFS0iTHLKOmnOZCa3eB2FlX0/html_content.jpeg?v=20220627161024",
            "capacity": 20,
            "price": 120,
        },
        {
            "title": "Quarto Privativo (cães)",
            "description": "Busca conforto e privacidade para o seu cãozinho? O quarto privativo é a opção ideal!",
            "image": "https://static.wixstatic.com/media/3c9e04_9e67eefb471c48b483a4aba70236fb3e~mv2_d_5175_3450_s_4_2.jpg/v1/fill/w_587,h_444,q_85,usm_0.66_1.00_0.01/3c9e04_9e67eefb471c48b483a4aba70236fb3e~mv2_d_5175_3450_s_4_2.jpg",
            "capacity": 2,
            "price": 250,
        },
        {
            "title": "Quarto Privativo (gatos)",
            "description": "Quarto privativo de alto padrão para o seu felino aproveitar com classe!",
            "image": "https://static.wixstatic.com/media/3c9e04_e6167e6e41a8456584250793ba200198~mv2_d_5093_3395_s_4_2.jpg/v1/fill/w_587,h_444,q_85,usm_0.66_1.00_0.01/3c9e04_e6167e6e41a8456584250793ba200198~mv2_d_5093_3395_s_4_2.jpg",
            "capacity": 2,
            "price": 250,
        },
    ]
    RoomType = apps.get_model("rooms", "RoomType")
    for room_type_data in data:
        RoomType.objects.create(**room_type_data)


def populate_rooms(apps, schema_editor):
    RoomType = apps.get_model("rooms", "RoomType")
    Room = apps.get_model("rooms", "Room")

    shared_room_type = RoomType.objects.get(title="Quarto Compartilhado")
    dog_room_type = RoomType.objects.get(title="Quarto Privativo (cães)")
    cat_room_type = RoomType.objects.get(title="Quarto Privativo (gatos)")

    Room.objects.create(room_type=shared_room_type)

    for _ in range(10):
        Room.objects.create(room_type=dog_room_type)
        Room.objects.create(room_type=cat_room_type)


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_room_types),
        migrations.RunPython(populate_rooms),
    ]
