# Generated by Django 4.1.5 on 2023-01-05 21:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("cat", "Cat"), ("dog", "Dog")], max_length=20
                    ),
                ),
                ("age", models.CharField(max_length=50)),
                ("neutered", models.BooleanField()),
                ("vaccinated", models.BooleanField()),
                ("docile", models.BooleanField()),
            ],
        ),
    ]
