# Generated by Django 4.1.5 on 2023-01-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[("cat", "Cat"), ("dog", "Dog")], max_length=20
            ),
        ),
    ]
