# Generated by Django 4.1.5 on 2023-01-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_auto_20230105_1847"),
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("active", "Active"),
                    ("concluded", "Concluded"),
                    ("cancelled", "Cancelled"),
                ],
                default="reserved",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="reservationservice",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
            ),
        ),
    ]
