# Generated by Django 4.1.5 on 2023-01-04 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_auto_20230103_1403"),
        ("services", "0002_auto_20230103_1420"),
        ("pets", "0002_rename_user_id_pet_user_alter_pet_type"),
        ("reservations", "0002_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationpet",
            name="pet",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationpet",
            name="room",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationservice",
            name="service",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("active", "Active"),
                    ("concluded", "Concluded"),
                    ("cancelled", "Cancelled"),
                ],
                default="reserved",
                max_length=9,
            ),
        ),
    ]
