# Generated by Django 4.1.5 on 2023-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_alter_reservation_status_alter_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("active", "Active"),
                    ("concluded", "Concluded"),
                    ("cancelled", "Cancelled"),
                ],
                default="reserved",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
