# Generated by Django 4.1.5 on 2023-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_text",
            field=models.TextField(),
        ),
    ]
